[project]
name = "ml-workshope-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "monish", email = "monish151mansuri@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
ml-workshope-project = "ml_workshope_project:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
